
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/klassno
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
jwt:
  secret: klassNosecretjwtsomeSYMbolsAND123123415315141DaasdjahsfkdashfoajfpasfhaofhJ21e31p2rjpiaefapsfjpaekfaoiHfeojsfhzsodfjdsklfjszdof
  expiration: 30000000
